name: 'Action of publish a monorepo'
description: 'publish a monorepo'
author: 'gz65555'

branding:
  icon: 'package'
  color: 'orange'

# Define your inputs here.
inputs:
  branches:
    description: 'set the branches to trigger the action'
    required: false

  packages:
    description: 'set the packages to upload'
    required: false

  publish:
    description: 'need publish or not'
    required: false
    default: true

runs:
  using: node20
  main: dist/index.js
