name: 'Action of publish a monorepo'
description: 'publish a monorepo'
author: 'gz65555'

branding:
  icon: 'package'
  color: 'orange'

# Define your inputs here.
inputs:
  branches:
    description: 'set the branches to trigger the action'
    required: false

runs:
  using: node20
  main: dist/index.js
